title: "図解 DBMS ~初心者が絵で理解する~"
summary: "データベース管理システム(DBMS)の基礎知識を学びました。\n文字だけだとイメージが沸きづらかったので図をたくさん使って整理しました。\n\n同じ様な方の役に立てれたら幸いです。\n\n※この本は筆者の理解に連動して追記修正される可能性があります。\n※またこちらは筆者が学習しながら執筆したものです。そのため誤字脱字や誤った知識を記載してしまう場合があります。"
topics: ["DBMS", "DB"]
published: false
price: 0
